Update types for h11 v0.14
encode/httpcore pull request #579
Opened 2022-09-25 18:31 UTC by madkinsz

This pull request extends and supersedes #526, updating the types for h11 0.14.0 which includes the upstream fix https://github.com/python-hyper/h11/commit/04cc0f781c47ebfb9f9b188a8e8aa423f276c0b1 allowing us to remove the cast and `isinstance` check from the hot loop which @graingert expressed concerns about in https://github.com/encode/httpcore/pull/526#discussion_r901134892.  A cast is still required for the return value as mypy is not type-narrowing on the `is` clause. We'd probably have to do a weird `isinstance/issubclass` combination to avoid the cast, which would bring us back to the original concerns about affected performance.

2022-09-25 18:32 UTC, madkinsz commented
Let me know if you'd like me to rebase or clean this history up. For now, I've just extended the commits from the original branch for clarity.

2022-09-26 10:57 UTC, tomchristie commented
> Let me know if you'd like me to rebase to clean this history up.

Not needed, no. We have "squash and merge" enforced on this project, so pull requests always end up as our atomic unit of history.

2022-09-26 11:01 UTC, tomchristie requested changes
A linting fix here...

2022-09-26 11:01 UTC, tomchristie commented on httpcore/_async/http11.py
> +
Looking at the continuous integration I think the listing requires this line to be removed.

The `scripts/lint` tool ought to do this for you automatically, or we can remove it as part of this review, through the GitHub interface.

Here's the commit suggestion...

```suggestion
```

2022-09-26 11:01 UTC, tomchristie commented on httpcore/_sync/http11.py
> +
We'd also drop this newline...

```suggestion
```

2022-09-27 11:55 UTC, tomchristie approved these changes

2022-09-27 11:56 UTC, merged