Change type of Extensions
encode/httpcore pull request #762
Opened 2023-07-28 11:39 UTC by karosis88

Closes #761 

# Checklist

-[x] Change type of the extensions.
-[x] Update changelog

2023-07-28 12:11 UTC, Pliner approved these changes

2023-07-28 14:13 UTC, Kludex requested changes

2023-07-28 14:13 UTC, Kludex commented on CHANGELOG.md
> +- Change the type of `Extensions` from `Mapping[Str, Any]` to `MutableMapping[Str, Any]`.
```suggestion
- Change the type of `Extensions` from `Mapping[Str, Any]` to `MutableMapping[Str, Any]`. (#762)
```

2023-07-28 14:17 UTC, Kludex approved these changes

2023-07-28 14:17 UTC, Kludex approved these changes

2023-07-28 14:17 UTC, karosis88 commented
Thank you @Kludex !

2023-07-28 14:17 UTC, merged

2023-08-01 13:34 UTC, tomchristie commented
Just coming back to this ...and... any reason for use to not use `Dict[...]` here instead?
Would that be preferable?

2023-08-01 13:42 UTC, karosis88 commented
It makes no difference for httpx; for httpcore, it's just a bit of reusability.

Other libraries built on top of httpcore can use more than just a dictionary.